name: typedoc

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install 

      - name: Build
        run: yarn run build

      - name: Generate typedoc
        run: yarn run docs

      - name: Publish to GitHub Pages
        uses: ./
        with:
          dir: docs
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
